server:
  port: 9999

spring:
  application:
    name: product-service

  main:
    web-application-type: none

  datasource:
    url: jdbc:mysql://localhost:3306/product-svc
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  zipkin:
    base-url: http://localhost:9411

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: product
    bootstrap-servers: localhost:29092
    config:
      topic:
        order: order