version: '3.8'

services:
  postgres:
    container_name: "postgres_risa"
    image: library/postgres:14
    ports:
      - "5432:5432"
    networks:
      - local_network
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_psql
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql


  keycloak:
    container_name: "keycloak_risa"
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_SCHEMA: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: user_db
      KC_DB_USERNAME: user_psql
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: true
    volumes:
      - ./rumah-indonesia-realm.json:/opt/keycloak/data/import/rumah-indonesia-realm.json
    ports:
      - "8080:8080"
    command:
      - "start-dev"
      - "--import-realm"
    depends_on:
      - postgres
    networks:
      - local_network

networks:
  local_network:
    name: local_network